Repository sahilsingh7735/hacktoberfest-Traveling-the-7-wonders-of-the-world, pull requests merged in 2022-10, with the labels that each got.

#15 created the navbar
  about.html
  assets/logo.jpeg
  css/navbar.css
  home.html
  profile.html
Labels: hacktoberfest, goodfirstissue, hacktoberfest2020, hacktoberfest-accepted

#27 :sparkles: What to pack page done
  what to pack/hostel.html
  what to pack/images/Journal.png
  what to pack/images/Trash Bin.png
  what to pack/images/UNO.png
  what to pack/images/backpack.png
  what to pack/images/blanket.png
  what to pack/images/boots.png
  what to pack/images/camera.png
  what to pack/images/first-aid-kit.png
  what to pack/images/gloves.png
  what to pack/images/knife.png
  what to pack/images/maps.png
  what to pack/images/mosquitoes.png
  what to pack/images/noise.png
  what to pack/images/pillow.png
  what to pack/images/sleeping bags.png
  what to pack/images/sleeping-mask.png
  what to pack/images/sunglasses.png
  what to pack/images/sweater.png
  what to pack/images/tent.png
  what to pack/images/toilet papers.png
  what to pack/images/torch.png
  what to pack/images/towel.png
  what to pack/images/watch.png
  what to pack/images/water-bottles (1).png
  what to pack/images/wireless-charger.png
  what to pack/index.html
  what to pack/style.css
  what to pack/tent.html
Labels: good first issue, hacktoberfest, hacktoberfest2020, hacktoberfest-accepted

#20 added the about page #14
  About.html
Labels: good first issue, hacktoberfest, hacktoberfest2020, hacktoberfest-accepted

#35 Arranging files
  about.html
  hostel.html
  index.html
  myStyle/sevenWonders.css
  myStyle/whatToPack.css
  profile.html
  sevenWonders.html
  tent.html
  what to pack/hostel.html
  what to pack/index.html
  what to pack/tent.html
  whatToPack.html
Labels: good first issue, hacktoberfest, first time only, goodfirstissue, hacktoberfest2020, hacktoberfest-accepted
